<a href="https://colab.research.google.com/github/krzysiekG-datascience/data-science/blob/main/01/02_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
v1 = np.array([3, 4])

In [9]:
v1

array([3, 4])

In [10]:
np.linalg.norm(v1)

5.0

In [11]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [13]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

In [14]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

Macierze mnozenie ez

In [16]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [18]:
Z = X.dot( Y)
Z

array([[ 2],
       [-6]])

In [19]:
Z.shape

(2, 1)

In [22]:
X = np.array([[2, -1 ,3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [25]:
np.dot(X, Y)


array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik

In [27]:
A = np.array([[2,4],
              [-1, 3]])
round(np.linalg.det(A))

10

In [29]:
np.trace(A)

5

In [31]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [32]:
A

array([[ 2,  4],
       [-1,  3]])

In [34]:
B = np.linalg.inv(A)
B


array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [36]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [37]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

Maciesz transponowana

In [38]:
A

array([[ 2,  4],
       [-1,  3]])

In [39]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [40]:
A.T

array([[ 2, -1],
       [ 4,  3]])

uklady rownan

In [41]:
A = np.array([[2, 4],
              [1, -1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [42]:
B = np.array([[10],
              [-1]])
B

array([[10],
       [-1]])

In [45]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

In [46]:
X

array([[1.],
       [2.]])

In [47]:
X.shape

(2, 1)