<a href="https://colab.research.google.com/github/krzysiekG-datascience/data-science/blob/main/01/wprowadzenie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.25.2'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 4.5])

In [ ]:
print(x)

[1.3 2.3 4.5]


In [ ]:
x.dtype

dtype('float64')

In [ ]:
x.shape

(3,)

In [ ]:
x.size

3

In [ ]:
x.ndim

1

2D array

In [ ]:
x = np.array([[1, 2, 3], [-2, 1, 5.5]])

In [ ]:
print(x)

[[ 1.   2.   3. ]
 [-2.   1.   5.5]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 3)

In [ ]:
x.dtype

dtype('float64')

In [ ]:
x = np.array([[1, 3, 5], [4, 2, 5]])

In [ ]:
print(x)

[[1 3 5]
 [4 2 5]]


In [ ]:
x.shape

(2, 3)

3D array

In [ ]:
x = np.array(
    [[[4, 3, 1],
      [3, 2, 1]],

      [[4, 1, 3],
       [4, 2, 1]],

     [[4, 1, 2],
      [4,1 , 2]]]
)

In [ ]:
x.ndim



3

In [ ]:
x.shape

(3, 2, 3)

In [ ]:
print(x)

[[[4 3 1]
  [3 2 1]]

 [[4 1 3]
  [4 2 1]]

 [[4 1 2]
  [4 1 2]]]


Typy danych

In [ ]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [ ]:
print(A)


[1. 2. 3.]


In [ ]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
A = np.array([1.2, 2.3, 3.5], dtype='int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False, False])

In [ ]:
A

array([ True, False, False])

In [ ]:
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 111], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

Tworzenie tablic

In [ ]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(5, 5), fill_value=4, dtype='int')

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=120, stop=55, step=-10)

array([120, 110, 100,  90,  80,  70,  60])

In [ ]:
np.arange(start=0, stop=1, step=0.05, )

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)

In [ ]:
A.reshape((5, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Operacje na tablicach

In [ ]:
A = np.array([1, 3, 5, 6])
B = np.array([11, 12, 13, 14])

In [ ]:
print(A)
print(B)

[1 3 5 6]
[11 12 13 14]


In [ ]:
A+B

array([12, 15, 18, 20])

In [ ]:
A-B



array([-10,  -9,  -8,  -8])

In [ ]:
B-A

array([10,  9,  8,  8])

In [ ]:
A / B

array([0.09090909, 0.25      , 0.38461538, 0.42857143])

In [ ]:
A + 3

array([4, 6, 8, 9])

In [ ]:
A = A + 1
print(A)

[2 4 6 7]


In [ ]:
print(A)
print(B)

[2 4 6 7]
[11 12 13 14]


In [ ]:
A + 1 *B

array([13, 16, 19, 21])

In [ ]:
np.add(A, B)

array([13, 16, 19, 21])

In [ ]:
np.subtract(A, B)

array([-9, -8, -7, -7])

In [ ]:
np.multiply(A, B)

array([22, 48, 78, 98])

In [ ]:
np.divide(A, B)

array([0.18181818, 0.33333333, 0.46153846, 0.5       ])

In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
X * Y

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X @ Y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
np.random.rand()

0.3687251706609641

In [ ]:
np.random.rand(10, 4)

array([[0.82099323, 0.09710128, 0.83794491, 0.09609841],
       [0.97645947, 0.4686512 , 0.97676109, 0.60484552],
       [0.73926358, 0.03918779, 0.28280696, 0.12019656],
       [0.2961402 , 0.11872772, 0.31798318, 0.41426299],
       [0.0641475 , 0.69247212, 0.56660145, 0.26538949],
       [0.52324805, 0.09394051, 0.5759465 , 0.9292962 ],
       [0.31856895, 0.66741038, 0.13179786, 0.7163272 ],
       [0.28940609, 0.18319136, 0.58651293, 0.02010755],
       [0.82894003, 0.00469548, 0.67781654, 0.27000797],
       [0.73519402, 0.96218855, 0.24875314, 0.57615733]])

In [ ]:
np.random.randint(10)

8

In [ ]:
np.random.randint(low=10, high=101)

36

In [ ]:
np.random.randint(low=10, high=101, size=10)

array([76, 62, 77, 71, 24, 14, 77, 21, 96, 87])

In [ ]:
np.random.randint(low=10, high=101, size=(10, 4))

array([[85, 66, 26, 34],
       [39, 31, 35, 90],
       [70, 71, 93, 43],
       [42, 80, 95, 41],
       [23, 81, 66, 34],
       [89, 51, 28, 50],
       [64, 89, 21, 48],
       [11, 54, 98, 34],
       [77, 92, 13, 86],
       [45, 96, 71, 79]])

In [ ]:
np.random.choice([4, 1, 3, 2])

2

In [ ]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [ ]:
data = np.arange(10)

In [ ]:
print(data)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np.random.shuffle(data)

In [ ]:
data

array([1, 7, 0, 5, 9, 3, 6, 2, 4, 8])

In [ ]:
data.shape

(10,)

Podstawowe wfunckje Np

In [3]:
np.exp(1)

2.718281828459045

In [4]:
np.sqrt(9)

3.0

In [8]:
np.all([2, 3, 1])

True

In [10]:
np.any([0, False])

False

In [12]:
bool(5)

True

In [15]:
A = np.random.rand(5)

In [16]:
A

array([0.69851174, 0.63674639, 0.58774865, 0.62870004, 0.74121857])

In [19]:
np.argmax(A)

4

In [20]:
A[np.argmax(A)]

0.7412185743367732

In [25]:
np.argmin(A)
A[np.argmin(A)]

0.5877486518342695

In [28]:
np.argsort(A)

array([2, 3, 1, 0, 4])

In [29]:
np.max(A)

0.7412185743367732

In [30]:
np.min(A)

0.5877486518342695

In [31]:
np.mean(A)

0.6585850792714381

In [32]:
np.median(A)

0.6367463870811143

In [33]:
np.std(A)

0.05442476665031097

Wycinanie


In [34]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [36]:
A[2]

2

In [37]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [40]:
A[:2]

array([0, 1])

In [41]:
A[0:2]

array([0, 1])

In [44]:
A[[0, 2]]

array([0, 2])

In [47]:
A = A.reshape(4, 5)

In [48]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [49]:
A[0]

array([0, 1, 2, 3, 4])

In [50]:
A[1]

array([5, 6, 7, 8, 9])

In [52]:
A[[0,1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
A[:, 0]

array([ 0,  5, 10, 15])

In [54]:
A[:, -1]

array([ 4,  9, 14, 19])

In [55]:
A[:, -2]

array([ 3,  8, 13, 18])

In [56]:
A[1,1]

6

In [57]:
A[1, 3]

8

In [58]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
A[[0,1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [62]:
A[1, 2] = 14

In [63]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [64]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [67]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [68]:
for row in A:
  print(row[1])

1
6
11
16


In [70]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [71]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [72]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [75]:
A.shape

(4, 5)

In [76]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [77]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [78]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [79]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Maski logiczne

In [80]:
A = np.arange(start=-10, stop=10, step=0.5)

In [81]:
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [83]:
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [84]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [85]:
A >= 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [88]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [89]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [91]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])